#pragma once
// BCH(31,21) + even parity, per RCR STD-42 §3.5.
//
// Every codeword is 32 bits, transmitted MSB first (§3.4). Bits 1..21 are the
// information bits, bits 22..31 the BCH check bits generated by dividing the
// information polynomial by
//
//     x^10 + x^9 + x^8 + x^6 + x^5 + x^3 + 1        (0x769)
//
// and bit 32 is an even parity bit over the whole codeword. The code has
// minimum distance 5, so up to two bit errors are correctable (§3.5.1).
//
// Bit numbering here follows the spec: codeword bit 1 is the MSB of the
// uint32_t (bit 31) and codeword bit 32 is the LSB (bit 0).

#include <cstdint>

namespace std42::pocsag {

// Generator polynomial x^10+x^9+x^8+x^6+x^5+x^3+1.
inline constexpr uint32_t kBchGenerator = 0x769u;

// Builds the syndrome → error-pattern table. Idempotent and thread-safe to
// call more than once; Receiver calls it on construction.
void bch_init();

// Corrects `cw` in place. Returns the number of bits corrected (0, 1 or 2), or
// -1 if the codeword is not correctable.
int bch_correct(uint32_t& cw);

// Syndrome of the 31 protected bits (parity bit excluded). Zero means the BCH
// part of the codeword is consistent.
uint32_t bch_syndrome(uint32_t cw);

} // namespace std42::pocsag
