#pragma once
// Shift-JIS (CP932) and JIS X 0201 decoding to UTF-8.
//
// RCR STD-42 defines two text message formats on top of the numeric one:
//   §3.6.2 カナ英数字 — JIS X 0201, 8 bits per character
//   §3.6.3 漢字       — Shift-JIS (JIS C 6226), 16 bits per character
//
// In both cases "各文字は、LSBから順次伝送される" — the bits of each character
// are sent least-significant first, which the message decoder undoes before
// handing the bytes here.

#include <cstdint>
#include <string>
#include <vector>

namespace std42::pocsag {

struct SjisEntry {
    uint16_t sjis;   // double-byte Shift-JIS code
    uint16_t ucs;    // Unicode BMP code point
};

// Generated by scripts/gen_sjis_table.py, sorted by `sjis`.
extern const SjisEntry kSjisTable[];
extern const unsigned kSjisTableSize;

// Single double-byte lookup. Returns 0 when the code is unassigned.
uint16_t sjis_lookup(uint16_t code);

// Appends `cp` to `out` as UTF-8.
void append_utf8(std::string& out, uint32_t cp);

// JIS X 0201 single byte → UTF-8 (0x20..0x7E roman, 0xA1..0xDF halfwidth
// katakana). Returns false for bytes with no mapping.
bool jisx0201_to_utf8(uint8_t b, std::string& out);

struct SjisDecodeResult {
    std::string text;        // UTF-8
    int chars = 0;           // characters produced
    int double_byte = 0;     // of which were double-byte
    int invalid = 0;         // bytes that could not be mapped
};

// Decodes a Shift-JIS byte stream. Unmappable bytes are emitted as U+FFFD and
// counted in `invalid`, so the caller can score the result.
SjisDecodeResult sjis_decode(const std::vector<uint8_t>& bytes);

} // namespace std42::pocsag
