#!/usr/bin/env python3
"""Generate src/pocsag/sjis_table.cpp — the Shift-JIS (CP932) → UTF-16 map.

RCR STD-42 §3.6.3 specifies the kanji message format as "シフトJIS規格16ビット
(JIS C 6226)".  Real municipal broadcast traffic uses the CP932 superset (NEC /
IBM extension rows), so the table is generated from Python's `cp932` codec.

The table is committed to the repository; regenerate with:
    python3 scripts/gen_sjis_table.py
"""
import sys, pathlib

def main() -> int:
    pairs = []
    for hi in range(0x81, 0xFD):
        for lo in range(0x40, 0xFD):
            if lo == 0x7F:
                continue
            b = bytes((hi, lo))
            try:
                ch = b.decode("cp932")
            except UnicodeDecodeError:
                continue
            if len(ch) != 1:
                continue
            cp = ord(ch)
            if cp > 0xFFFF:
                print(f"non-BMP mapping {b.hex()} -> U+{cp:X}", file=sys.stderr)
                return 1
            pairs.append(((hi << 8) | lo, cp))

    pairs.sort()
    out = [
        "// Generated by scripts/gen_sjis_table.py — do not edit by hand.",
        "// Shift-JIS (CP932) double-byte code -> Unicode BMP code point.",
        "",
        '#include "pocsag/sjis.h"',
        "",
        "namespace std42::pocsag {",
        "",
        f"extern const SjisEntry kSjisTable[] = {{",
    ]
    for i in range(0, len(pairs), 6):
        row = "    " + " ".join(
            f"{{0x{s:04X},0x{u:04X}}}," for s, u in pairs[i:i + 6]
        )
        out.append(row)
    out += [
        "};",
        "",
        f"extern const unsigned kSjisTableSize = {len(pairs)}u;",
        "",
        "} // namespace std42::pocsag",
        "",
    ]

    dst = pathlib.Path(__file__).resolve().parent.parent / "src/pocsag/sjis_table.cpp"
    dst.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {dst} ({len(pairs)} entries)")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
